version: '3'

services:
  mongo:
    image: mongo:latest
    container_name: mongo-container
    environment:
      - MONGO_INITDB_ROOT_USERNAME=root
      - MONGO_INITDB_ROOT_PASSWORD=password
    volumes:
      - mongo-data:/data/db
    ports:
      - "27017:27017"
    networks:
      - mongo-network

  mongo-express:
    image: mongo-express:latest
    container_name: mongo-express-container
    environment:
      - ME_CONFIG_MONGODB_SERVER=mongo
      - ME_CONFIG_MONGODB_PORT=27017
      - ME_CONFIG_MONGODB_ADMINUSERNAME=root  # Đảm bảo đúng username
      - ME_CONFIG_MONGODB_ADMINPASSWORD=password  # Đảm bảo đúng password
    ports:
      - "8085:8081"
    networks:
      - mongo-network
    depends_on:
      - mongo

networks:
  mongo-network:
    driver: bridge

volumes:
  mongo-data:
    driver: local
