version: '3.8'

services:
  mysql:
    image: mysql:8.0
    container_name: mysql-bai2-bai3
    ports:
      - "3308:3306"  # Mở cổng 3308 trong container lên cổng 3307 trên máy host
    environment:
      MYSQL_DATABASE: mydb
      MYSQL_USER: user
      MYSQL_PASSWORD: password
      MYSQL_ROOT_PASSWORD: root
    networks:
      - mysql_network

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: phpmyadmin-bai2
    ports:
      - "8081:80"  # Mở cổng 80 trong container lên cổng 8081 trên máy host
    environment:
      PMA_HOST: mysql-bai2-bai3  # Tên container MySQL, dùng để kết nối
      PMA_USER: user
      PMA_PASSWORD: password
    networks:
      - mysql_network
    depends_on:
      - mysql

networks:
  mysql_network:
    driver: bridge
