version: '3'

services:
  # Dịch vụ MySQL
  mysql:
    image: mysql:latest
    container_name: mysql-container-bai8
    environment:
      - MYSQL_ROOT_PASSWORD=rootpassword
      - MYSQL_DATABASE=mydb
      - MYSQL_USER=user
      - MYSQL_PASSWORD=userpassword
    ports:
      - "3309:3306"
    networks:
      - app-network
    volumes:
      - mysql-data:/var/lib/mysql

  # Dịch vụ Node.js
  app:
    build: ./app
    container_name: node-app
    ports:
      - "3030:3000"
    environment:
      - DB_HOST=mysql
      - DB_PORT=3306
      - DB_USER=user
      - DB_PASSWORD=userpassword
      - DB_NAME=mydb
    networks:
      - app-network
    depends_on:
      - mysql

networks:
  app-network:
    driver: bridge

volumes:
  mysql-data:
    driver: local
